# Generated by Django 5.1.7 on 2025-05-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('cert_id', models.CharField(max_length=20, unique=True)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Sertifikatlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses', models.CharField(choices=[('001', 'KS'), ('002', 'Photoshop'), ('003', 'Web'), ('004', '3Dmax'), ('005', 'Admin'), ('006', 'Python'), ('007', 'Foundation'), ('008', 'Web dasturlash'), ('009', 'MS Word')], default='001', max_length=5)),
            ],
        ),
    ]
