# Generated by Django 5.1.7 on 2025-05-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sertificats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='date',
            field=models.CharField(max_length=20),
        ),
    ]
