# Generated by Django 5.2.1 on 2025-05-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sertificats", "0002_alter_certificate_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="template",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
